config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :memberships

  resources :clubs do
    resources :shelves do
      resources :books do
        member do
          patch :set_as_current
        end
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
  end

  get '/about', to: 'static#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  namespace :admin do 
    resources :users
  end

  delete '/signout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/club.rb
# 1. Confirm relationships are appropriate

class Club < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_one :shelf, :dependent => :destroy
    has_many :books, through: :shelf, :dependent => :destroy
    has_many :discussions, through: :books, :dependent => :destroy
    has_many :comments, through: :discussions, :dependent => :destroy

    has_many :memberships, :dependent => :destroy
    has_many :users, through: :memberships, :dependent => :destroy

    acts_as_followable
    acts_as_likeable

    mount_uploader :club_image, AvatarUploader
    mount_uploader :cover_image, AvatarUploader

    validates_processing_of :club_image
    validates_processing_of :cover_image
    validate :image_size_validation

    validates :name, presence: {:message => 'cannot be blank, club cannot be saved.'}
    validates :genre, presence: {:message => 'cannot be blank, club cannot be saved.'}
    validates :subgenre, presence: {:message => 'cannot be blank, club cannot be saved.'}
    validates :description, presence: {:message => 'cannot be blank, club cannot be saved.'}

    
    def self.categorize_by(genre)
        Club.all.where(:genre => genre)
    end

    private

    def image_size_validation
        if club_image.size > 0.5.megabytes
            errors[:club_image] << "should be less than 500KB" 
        elsif
            cover_image.size > 0.5.megabytes
            errors[:cover_image] << "should be less than 500KB" 
        end
    end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_club, except: [:index, :new, :create]

    def index
        @clubs = Club.all
        @genres = ["Action", "Adventure", "Classic", "Comedy", "Crime", "Drama", "Dystopia", "Fantasy", "General", "Historical", "Horror", "Mystery", "Non-fiction", "Romance", "Satire", "Sci-Fi", "Tech", "Thriller", "YA-Fiction"]

        respond_to do |format|
            format.html { render :index }
            format.json { render :json => @clubs }
        end

    end

    def new
        @club = Club.new
        @genres = ["Action", "Adventure", "Classic", "Comedy", "Crime", "Drama", "Dystopia", "Fantasy", "General", "Historical", "Horror", "Mystery", "Non-fiction", "Romance", "Satire", "Sci-Fi", "Tech", "Thriller", "YA-Fiction"]
    end

    def create
        @club = Club.create(club_params)

        if @club.save
            @shelf = Shelf.create(:club_id => @club.id)
            @membership = Membership.create(:user_id => current_user.id, :club_id => @club.id)
            current_user.follow!(@club)
            @membership_status = @club.memberships.find_by_user_id(current_user.id)
            @membership_status.admin = true
            @membership_status.save!
            redirect_to @club
        else
            if @club.errors.any?
                @club.errors.full_messages.each do |msg|
                    flash[:danger] = msg
                end
            end
            redirect_to new_club_path
        end
    end

    def show
        @membership_status = @club.memberships.find_by_user_id(current_user.id)
        @admin_membership = @club.memberships.where(admin: 1)
        @admin = User.find(@admin_membership.pluck(:user_id).join(""))

        @followers = @club.followers(User)

        @shelf = @club.shelf
        @current_book = Book.find(@shelf.current_book) if @shelf.current_book
        @upcoming_books = @shelf.upcoming_books.compact.map { |book| Book.find(book) }
        @read_books = @shelf.read_books.compact.map { |book| Book.find(book) }

        respond_to do |format|
            format.html { render :show }
            format.json { render :json => @club }
        end
     
    end

    def edit
        membership = @club.memberships.find_by_user_id(current_user.id)
        if membership.admin = true
            render 'edit'
        else
            flash[:danger] = "You are not an admin of this club."
            redirect_to @club
        end
    end

    def update
        if @club.update(club_params)
            flash[:success] = "The club is successfully updated."
            redirect_to @club
        else
            flash[:danger] = "The club could not be updated."
            render 'edit'
        end
    end

    def destroy
        @club.destroy
        redirect_to memberships_path
    end
 
    private

    def set_club
        @club = Club.friendly.find(params[:id])
    end

    def club_params
        # params.require(:club).permit(:id, :name, :genre, :subgenre, :description)
        params.fetch(:club, {}).permit(:id, :name, :genre, :subgenre, :description)
    end

end

app/helpers/clubs_helper.rb
module ClubsHelper
 
    def full_name(user)
        "#{user.first_name} #{user.last_name}"
      end

    def link_to_toggle_club_follow(club)
        url = membership_path(club)

        if club.followed_by?(current_user)
            link_to("Following", url, {
                method: 'DELETE',
                remote: true,
                class: 'follow btn btn-secondary',
            })
        else
            link_to("Follow", url, {
                method: 'PUT',
                remote: true,
                class: 'follow btn btn-primary',
            })
        end
    end

    def show_follower_count(club)
        pluralize(club.followers_count, "Follower")
    end

end

app/views/clubs/_shelf.html.erb
<h1 class="sub">Current Book</h1>
    <% if @current_book %>
        <div class="book-grid-wrapper">
            <div class="book-grid">
                <%= image_tag @current_book.image %>
                <p><%= link_to @current_book.title, club_shelf_book_path(:club_id => params[:id], :shelf_id => @current_book.shelf_id, :id => @current_book.id ) %></p>
            </div>
        </div>
    <% else %>
            <p>This club is currently not reading.</p>
    <% end %>

<div class="inline">
    <h1 class="sub">Upcoming Books</h1>
    <%= button_to "Add a Book", { :action => "new", :controller => "books", :club_id => params[:id], :shelf_id => @shelf.id }, :class => "btn btn-primary", :method => "get" %>
</div>

<% if !@shelf.upcoming_books.empty? %>
    <div class="book-grid-wrapper">
        <% @upcoming_books.each do |book| %>
            <div class="book-grid">
                <%= image_tag book.image %>
                <p><%= link_to book.title, club_shelf_book_path(:club_id => params[:id], :shelf_id => book.shelf_id, :id => book.slug ) %></p>
            </div>
        <% end %>
    </div>
<% else %>
        <p>This club has no upcoming books to read.</p>
<% end %>

<h1 class="sub">Read Books</h1>
<% if !@shelf.read_books.empty? %>
    <div class="book-grid-wrapper">
        <% @read_books.each do |book| %>
            <div class="book-grid">
                <%= image_tag book.image %>
                <p><%= link_to book.title, club_shelf_book_path(:club_id => params[:id], :shelf_id => book.shelf_id, :id => book.id ) %></p>
            </div>
        <% end %>
    </div>
<% else %>
    <p>This club has not finished reading any book yet.</p>
<% end %>

app/views/clubs/edit.html.erb
<h1 class="center">Edit Club</h1>

<%= simple_form_for @club, 
  wrapper: :floating_labels_form,
  defaults: { input_html: { style: 'height: 60px' } } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :genre, collection: @genres, label_html: { class: 'style-label' } %>

  <%= f.input :subgenre, as: :string %>

  <%= f.input :description, as: :string %>
  
  <%# <%= f.input :club_image %>

  <%# <%= f.input :cover_image %>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/clubs/index.html.erb
<%# 1. Restrict books browsing for logged in users %>
<%# 2. Allow users to join clubs %>
<%# 3. Allow users to view a club %>
<%# 4. Allow users to create a club %>
<%# 5. Allow users to suggest one book %>
<h1 class="center">Club Index Page</h1>

<% if @clubs.empty? %>
    Oops! There are no clubs yet. Why not start your own?
<% else %>
    <div class="grid-wrapper">
        <% @genres.each do |genre| %>
            <div class="tags grid">
                <p class="genre tag <%= genre.downcase %> "><%= genre %></p>

                <div class="club-wrapper-box">
                    <ul>
                        <% @clubs.categorize_by(genre).each do |club| %>
                            <% if club.nil? || club.name.nil? %>
                                There is no club in this genre yet.
                            <% else %>
                                <li>
                                    <%= link_to club.name, club_path(club) %>
                                    <%# <%= link_to_toggle_club_follow club %>
                                </li>                            
                            <% end %>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/clubs/new.html.erb
<%# 1. Create form_for @club with appropriate fields, routes and redirects — include sticky code of conduct (default) %>
    <%# Title %>
    <%# Description %>
    <%# Genre %>
    <%# Random or Selection %>
    <%# Add Book %>
    <%# Code of Conduct %>

<h1 class="center">New Club</h1>

<%= simple_form_for @club, 
  wrapper: :floating_labels_form,
  defaults: { input_html: { style: 'height: 60px' } } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :genre, collection: @genres, label_html: { class: 'style-label' }, include_blank: 'Select main genre' %>

  <%= f.input :subgenre, as: :string %>
  
  <%= f.input :description %>

  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/clubs/show.html.erb
<%# 1. Do not restrict club browsing for logged in users %>
<%# 2. Allow users to join club if not joined %>
<%# 3. Show current read, club title, club description, club cover %>
<%# 4. Show member count, member list, and admin %>
<%# 5. Show club shelf %>
<%# 6. Allow club members to add one book to club shelf %>
<%# 7. Guide users on how to start a discussion thread %>
<%# 8. Allow users to participate in existing discussion thread, regardless of clubs %>
<%# 9. Add a sticky code of conduct sidebar %>

<div class="club-wrapper">
    <div class="club">

        <h1><%= @club.name %></h1>

        <div class="tags">
            <p class="genre tag <%= @club.genre.downcase %> "><%= @club.genre %></p>
            <p class="subgenre tag"><%= @club.subgenre %></p>
        </div>

        <p><%= @club.description %> <br/>
        Admin: <%= link_to full_name(@admin), admin_user_path(@admin) %> </p>

        <div class="follow-details">
            <%= link_to_toggle_club_follow @club %>
            <%= show_follower_count(@club) %>
            
            <% @followers.each do |follower| %>
                <%= link_to full_name(follower), admin_user_path(follower) %>
                <%=  %>
            <% end %>
        </div>

        <div class="shelf-wrapper">
            <%= render "shelf" %>
        </div>

        <div class="buttons">
            <% if !@membership_status.nil? && @membership_status.admin == true %>
                <%= button_to "Edit Club", edit_club_path, method: "get", class: "btn btn-primary btn-md" %>

                <%= button_to 'Delete Club', { :controller => :clubs, :action => 'destroy' }, method: "delete", class: "btn btn-danger btn-md", data: { :confirm => 'Are you sure?' } %>
            <% end %>
        </div>

    </div>

    <div class="code-of-conduct">
        <h1>Code of Conduct</h1>
        <p><i>The following is taken from the <a href="https://www.contributor-covenant.org/version/1/4/code-of-conduct">Contributor Covenant:</a>.</i></p>
        <p>In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.</p>
        
        <p>Examples of behavior that contributes to creating a positive environment include:</p>
        <ul>
            <li>Using welcoming and inclusive language</li>
            <li>Being respectful of differing viewpoints and experiences</li>
            <li>Gracefully accepting constructive criticism</li>
            <li>Focusing on what is best for the community</li>
            <li>Showing empathy towards other community members</li>
        </ul>

        <p>Examples of unacceptable behavior by participants include:</p>
        <ul>
            <li>The use of sexualized language or imagery and unwelcome sexual attention or advances</li>
            <li>Trolling, insulting/derogatory comments, and personal or political attacks</li>
            <li>Public or private harassment</li>
            <li>Publishing others’ private information, such as a physical or electronic address, without explicit permission</li>
            <li>Other conduct which could reasonably be considered inappropriate in a professional setting</li>
        </ul>

        <p>Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at <strong>janicedarikho@gmail.com</strong>. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.</p>

        <p>Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project’s leadership.</p>
    </div>
</div>