config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :memberships

  resources :clubs do
    resources :shelves do
      resources :books do
        member do
          patch :set_as_current
        end
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
  end

  get '/about', to: 'static#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  namespace :admin do 
    resources :users
  end

  delete '/signout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :club
    belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_user

    def index
        @clubs = @user.followees(Club)
        @genres = @clubs.map { |club| club.genre }.uniq

        respond_to do |format|
            format.html { render :index }
            format.json { render :json => @clubs }
        end
    end

    def new
        @club = Club.friendly.find(params[:club_id])
        if @user.follows?(@club) == true
            flash[:notice] = "You have already joined #{@club.name}."
            redirect_to memberships_path
        else
            @membership = Membership.create(:user_id => params[:user_id], :club_id => params[:club_id])
            @club.users << @user
            @user.follow!(@club)
            flash[:success] = "You have successfully joined #{@club.name}."
            redirect_to memberships_path
        end
    end
    
    def update
        @club = Club.friendly.find(params[:id])
        @user.follow!(@club)
        respond_to do |format|
            format.js { render inline: "location.reload();" }
        end
    end

    def destroy
        @club = Club.friendly.find(params[:id])
        @user.unfollow!(@club)
        respond_to do |format|
            format.js { render inline: "location.reload();" }
        end 
    end

    private

    def set_user
        @user = current_user
    end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/index.html.erb
<h1 class="center">Clubs You Follow</h1>

<% if @clubs.empty? %>
    You haven't joined any clubs yet. Why not start your own?
<% else %>
    <div class="grid-wrapper">
        <% @genres.each do |genre| %>
            <div class="tags grid">
                <p class="genre tag"></p>

                <div class="club-wrapper-box">
                    <ul>
                        <% @clubs.each do |club| %>
                            <% if club.genre == genre %>
                                <li>
                                    <%= link_to club.name, club_path(club) %>
                                </li>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
    </div>

<% end %>

<%= button_to "Create A New Club", new_club_path, { method: 'get', class: "btn btn-primary" } %>