config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :memberships

  resources :clubs do
    resources :shelves do
      resources :books do
        member do
          patch :set_as_current
        end
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
  end

  get '/about', to: 'static#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  namespace :admin do 
    resources :users
  end

  delete '/signout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :shelves, through: :clubs
  has_many :books, through: :shelves

  has_many :comments
  has_many :discussions

  acts_as_follower
  acts_as_mentionable

  mount_uploader :image, AvatarUploader

  validates :email, uniqueness: {:message => 'is already taken, user cannot be saved.' }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
      u.username = auth['info']['name'].downcase.gsub(/\s+/, '')
      u.first_name = auth['info']['name'].partition(" ").first
      u.last_name = auth['info']['name'].partition(" ").last
      u.email = auth['info']['email']
      u.remote_image_url = auth['info']['image'].gsub('http', 'https')
      u.password = Devise.friendly_token[0,20]
    end
  end

  def country_name
    country = ISO3166::Country[location]
    if country.nil?
      "Hogwarts School of Witchcraft and Wizardry"
    else
      country.translations[I18n.locale.to_s] || country.name
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

    before_action :authenticate_user!

    def show
        @user = User.friendly.find(params[:id])
        @clubs = @user.followees(Club)
        @quote_hash = Libri::Scraper.new.scrape_quote.sample
        @quote = @quote_hash.quote
        @author = @quote_hash.author
    end

    def edit
        @user = User.friendly.find(params[:id])
    end

    def update
        @user = User.friendly.find(params[:id])
        @user.update(admin_user_params)
        redirect_to admin_user_path(@user)
    end

    private

    def admin_user_params
        params.require(:user).permit(:image, :username, :first_name, :last_name, :location, :bio, :gender, :location, :twitter, :facebook, :instagram, :slack)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user      
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/users_helper.rb
module UsersHelper

  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end

  def show_bio(user)
    user.bio.nil? || user.bio == "" ? "Add your introduction here!" : user.bio
  end

  def show_clubs(user)
    clubs = user.followees(Club)
    html = ''
    if clubs.empty?
        if user == current_user
            "You have not joined any club yet."
        else
            "This user has not joined any club yet."
        end
    else
        clubs.each do |club|
            html += link_to(club.name, club_path(club))
        end
        return html.html_safe
    end
  end

  def show_socials(user, social)
    content = content_tag(:i, "", class: "fab fa-#{social}")

    if social == "twitter" && user.twitter != "" && user.twitter
        html = 'https://twitter.com/'
        social_link = html + user.twitter 
    elsif social == "facebook" && user.facebook != "" && user.facebook
        html = 'https://www.facebook.com/'
        social_link = html + user.facebook
    elsif social == "instagram" && user.instagram != "" && user.instagram
        html = 'https://www.instagram.com/'
        social_link = html + user.instagram
    elsif social == "slack" && user.slack != "" && user.slack
        html = 'https://rebelbasetalk.slack.com/team/'
        social_link = html + user.slack
    else
        content = ""
    end
    
    content_tag(:a, content, href: social_link)
  end

  def random_book_quote(quote, author)
    "#{quote} — #{author}"
  end


end

app/views/admin/users/edit.html.erb
<%= simple_form_for ([:admin, @user]), wrapper: :floating_labels_form do |f| %>

  <h1 class="center">Edit User Profile</h1>

  <%= f.error_notification %>

  <%= f.input :username, required: true %>

  <%= f.input :first_name, required: true %>

  <%= f.input :last_name, required: true %>
  
  <%= f.input :bio %>
  
  <div class="form-label-group select optional user_location">
    <%= f.country_select :location, {}, { include_blank: 'Select a country', class: 'form-control select optional' } %>
    <%= f.label :location, class: 'style-label' %>
  </div>

  <%= f.input :twitter %>
  
  <%= f.input :facebook %>
  
  <%= f.input :instagram %>

  <%= f.input :slack %>

  <%= f.input :image, label: 'Profile Image' %>

  <%= f.button :submit, class: "btn-primary" %>

<% end %>

app/views/admin/users/show.html.erb
<%# 1. Add Slack link %>
<%# 2. Add books read and clubs part of %>
<div class="profile-wrapper">

    <div class="primary-profile">
        <%= image_tag @user.image.url %>

        <h1 class="non"><%= full_name(@user) %></h1>

        <i class="fas fa-map-marker-alt"></i>
        <%= @user.country_name  %>
    </div>

    <div class="secondary-profile">
        <h1 class="sub">Bio</h1>
            <%= show_bio(@user) %>
        
        <h1 class="sub">Clubs</h1>
            <%= show_clubs(@user) %>
    </div>
        
    <div class="social">
        <h1 class="sub">Find me on</h1>
            <%= show_socials(@user, 'twitter') %>
            <%= show_socials(@user, 'facebook') %>
            <%= show_socials(@user, 'instagram') %>

        <h1 class="sub">Let's chat on Slack</h1>
            <%= show_socials(@user, 'slack') %>
    </div>

</div>

<p class="narrow center">
    <%= random_book_quote(@quote, @author) %>
</p>

<%= button_to "Edit profile", edit_admin_user_path, { method: 'get', class: 'btn btn-primary' } %>