config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :memberships

  resources :clubs do
    resources :shelves do
      resources :books do
        member do
          patch :set_as_current
        end
        resources :discussions do
          delete "destroy"
          resources :comments do
            delete "destroy"
          end
        end
      end
    end
  end

  get '/about', to: 'static#about'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  namespace :admin do 
    resources :users
  end

  delete '/signout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'

end

app/views/layouts/_footer.html.erb
<footer>
    <p>Explore hundreds of books meticulously handpicked by people like you. © 2018 rebelbase</p>
    <div class="social">
        <a href="https://github.com/jouissances/rebel-base"> <i class="fab fa-github"></i></a>
        <a href="#"> <i class="fab fa-facebook"></i></a>
        <a href="#"> <i class="fab fa-instagram"></i></a>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="logo">
        <%= link_to image_tag("/images/logo.png"), root_path %>
        <%= link_to "Clubs", clubs_path  %>
    </div>
    
    <nav>
        <%= link_to "About", about_path  %>
        
        <% if user_signed_in? %>
            <%= link_to "Membership", memberships_path %>

            <% if current_user.image.cover.url %>
                <%= link_to image_tag(current_user.image.cover.url), admin_user_path(current_user) %>
            <% else %>
                <%= link_to "Profile", admin_user_path(current_user) %>
            <% end %>
            
            <%= link_to "Account", edit_user_registration_path %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Log In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RebelBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.3.1/css/all.css" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == 'notice' || key == 'alert' ? 'primary' : key  %>"><%= value %></div>
      <% end %>

    <section class="content">
      <%= yield %>
    </section>

    <%= render 'layouts/footer' %>

  </body>
</html>